GET http://0.0.0.0:3000/api


GET http://0.0.0.0:3000/api/users/getManny/
athorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NTNlY2UxZDc2MGEzZWFmYTkzNjM2MiIsIm5vbWJyZSI6ImFkbWluIiwiZW1haWwiOiJtYWdudXNjb2x0ZWxsb0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IlNBRkEyMDIyIiwiZWRhZCI6MSwiZGlzY29yZCI6Im1hbm55MTkwOSM0NTA2IiwiZXN0YWRvIjoiNjQ1M2VjZTFkNzYwYTNlYWZhOTM2MzU5Iiwib2JzZXJ2YWNpb25lcyI6InJlZ2lzdHJhZG8gcG9yIG1lZGlvIGRlIGxvcyBzZWVkZXJzIiwiX192IjowfSwiaWF0IjoxNjgzNDg5MTU1fQ._ZudJrkFPTkRi1sgtrsIMs2rTUspJjSD4ZAkMaUMRf0

GET http://0.0.0.0:3000/api/users/getManny/
athorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NTM1YWE0Njg5NzZiOWNhNmFjZTFkZiIsInJvbCI6IjY0NTM1YWE0Njg5NzZiOWNhNmFjZTFkYiIsIm5vbWJyZSI6ImFkbWluIiwiZW1haWwiOiJtYWdudXNjb2x0ZWxsb0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IlNBRkEyMDIyIiwiZWRhZCI6MSwiZGlzY29yZCI6Im1hbm55MTkwOSM0NTA2IiwiZXN0YWRvIjoiNjQ1MzVhYTQ2ODk3NmI5Y2E2YWNlMWQ0Iiwib2JzZXJ2YWNpb25lcyI6InJlZ2lzdHJhZG8gcG9yIG1lZGlvIGRlIGxvcyBzZWVkZXJzIiwiX192IjowfSwiaWF0IjoxNjgzMTg0MzkzfQ.inw98qau-B2fDSn0GP7EI1sz2yWpbZtETrmx0c82q-E

POST http://0.0.0.0:3000/api/users/signIn/
Content-Type: application/json

{
    "email": "magnuscoltello@gmail.com",
    "password": "SAFA2022"
}

POST http://0.0.0.0:3000/api/users/signIn/
Content-Type: application/json

{
    "email": "safagestion2022@gmail.com",
    "password": "SAFA2022"
}

POST http://0.0.0.0:3000/api/users/signUp/
Content-Type: application/json

{
    "user":
        {
        "nombre": "Galileu Goodfellaaa",
        "email": "galileooo@gmail.com",
        "password": "SAFA2022"
        }
}
